- name: test FIGlet
  hosts: localhost
  gather_facts: false
  tasks:
    - name: figlet
      include_tasks: "figlet.yml"
      loop:
        - big
        - block
        - bubble
        - digital
        - lean
        - smscript
        - smslant
        - xsbook
